### ISSUE TITLE
Installation program 

### ISSUE THREAD

**Issue by ashu-py** [vedic-lang/vedic#1]
I am using termux .I am facing problem by every method .

**Comment by PtPrashantTripathi** [comment]
@ashu-py  nobody can help you when you say "I facing problem..." or "... does not work". You should give more details about what happens when you try something. 

For example:
When I try to ... app displays error message with text "..."

Attach screenshot if possible. 

Please note: "I can't..." and "I do not know how to..." are different issues! 
- If you do not know how to use some feature then ask about it and we will help you. 
- If you know how to use it but it does not work properly please tell what do you do and which result do you get.
